#!/usr/bin/env bash

# Check if all four arguments are  provided
if [ "$#" -lt 4 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assigning arguments to variables
path_to_file="$1"
ip="$2"
username="$3"
path_to_ssh_key="$4"

# Transferring the file using scp
scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$ip":~/ 

# Checking if scp command executed successfully
if [ "$?" -eq 0 ];
then
	echo "File transferred successfully"
else
	echo "File transfer failed"
fi
