#!/usr/bin/env bash

# Set the hostname for web servers
HOSTNAME_PREFIX=463080
WEB_SERVER_1="18.233.66.2-web-01"
WEB_SERVER_2="54.87.238.243-web-02"

# Install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 463080-web-01 18.233.66.2:80 check
    server 463080-web-02 54.87.238.243:80 check
EOF

# Restart HAProxy
sudo systemctl restart haproxy

# Enable HAProxy init script
sudo systemctl enable haproxy

echo "HAProxy installed and configured successfully."
