#!/usr/bin/env bash
# Debbugging fixes for nginx

# Link default file from sites-available to sites-enabled directory
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart
